title: Bayu Angora
baseURL: /

params:
  domain: angora.id
  menu1: blog
  menu2: poem
  menu3: quote
  menusize: 10%
  color1: black
  color2: white
  color3: red
  background: https://loremflickr.com/300/600/abstract
  fontlink: /font.woff2
  description: Keep On Rocking!
  copyright: • Bayu Angora (C) All Rights Reserved •
  copyrightlink: https://s.id/sitelock
