title: Bayu Angora
baseURL: /

params:
  domain: angora.id
  menu1: post
  menu2: grade
  menu3: score
  menusize: 36px
  color1: black
  color2: white
  color3: red
  background: 
  fontlink: /font.woff2
  description: Keep On Rocking!
  copyright: • Bayu Angora (C) All Rights Reserved •
  copyrightlink: https://s.id/sitelock
